### ISSUE TITLE
Installation on a OS X Yosemite fails

### ISSUE THREAD

**Issue by zaks** [snmsts/homebrew-roswell#1]
sh-3.2# brew install roswell
==> Installing roswell from snmsts/homebrew-roswell
==> Downloading https://github.com/snmsts/roswell/archive/v0.0.3.46.tar.gz
######################################################################## 100.0%
==> sh bootstrap
==> ./configure --prefix=/usr/local/Cellar/roswell/0.0.3.46
==> make install
Installing sbcl-bin...
########################################################################## 100%
/bin/sh: line 1: 71865 Segmentation fault: 11  ./ros ../scripts/man.ros ../documents/ros.html ../documents/ros.1
make[1]: *** [../documents/ros.1] Error 139
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):

**Comment by snmsts** [comment]
Hm... Would you show me the result of 'brew -v install roswell'?

**Comment by zaks** [comment]
Sure

sh-3.2# brew -v install roswell
Homebrew 0.9.5
==> Installing roswell from snmsts/homebrew-roswell
==> Downloading https://github.com/snmsts/roswell/archive/v0.0.3.46.tar.gz
Already downloaded: /Library/Caches/Homebrew/roswell-0.0.3.46.tar.gz
==> Verifying roswell-0.0.3.46.tar.gz checksum
tar xf /Library/Caches/Homebrew/roswell-0.0.3.46.tar.gz
==> sh bootstrap
configure.ac:14: installing './compile'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
src/Makefile.am:34: warning: CLEANFILES multiply defined in condition TRUE ...
src/Makefile.am:28: ... 'CLEANFILES' previously defined here
src/Makefile.am: installing './depcomp'
==> ./configure --prefix=/usr/local/Cellar/roswell/0.0.3.46
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of clang... gcc3
checking for main in -lwininet... no
checking for curl_global_init in -lcurl... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
==> make install
Making install in src
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT lsp.o -MD -MP -MF .deps/lsp.Tpo -c -o lsp.o lsp.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT opt.o -MD -MP -MF .deps/opt.Tpo -c -o opt.o opt.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT download.o -MD -MP -MF .deps/download.Tpo -c -o download.o download.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT archive.o -MD -MP -MF .deps/archive.Tpo -c -o archive.o archive.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT html.o -MD -MP -MF .deps/html.Tpo -c -o html.o html.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT util_list.o -MD -MP -MF .deps/util_list.Tpo -c -o util_list.o util_list.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT util_string.o -MD -MP -MF .deps/util_string.Tpo -c -o util_string.o util_string.c
mv -f .deps/archive.Tpo .deps/archive.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT util_dir.o -MD -MP -MF .deps/util_dir.Tpo -c -o util_dir.o util_dir.c
mv -f .deps/download.Tpo .deps/download.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT util_system.o -MD -MP -MF .deps/util_system.Tpo -c -o util_system.o util_system.c
mv -f .deps/util_list.Tpo .deps/util_list.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-internal.o -MD -MP -MF .deps/cmd-internal.Tpo -c -o cmd-internal.o cmd-internal.c
mv -f .deps/opt.Tpo .deps/opt.Po
printf "#define ROS_COMPILE_ENVIRONMENT \"%s\"\n" "`clang --version|head -n 1`" > gend.h.tmp
mv -f .deps/util_string.Tpo .deps/util_string.Po
mv -f .deps/util.Tpo .deps/util.Po
mv -f .deps/lsp.Tpo .deps/lsp.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run.o -MD -MP -MF .deps/cmd-run.Tpo -c -o cmd-run.o cmd-run.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-sbcl.o -MD -MP -MF .deps/cmd-run-sbcl.Tpo -c -o cmd-run-sbcl.o cmd-run-sbcl.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-ccl.o -MD -MP -MF .deps/cmd-run-ccl.Tpo -c -o cmd-run-ccl.o cmd-run-ccl.c
mv -f .deps/html.Tpo .deps/html.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-clisp.o -MD -MP -MF .deps/cmd-run-clisp.Tpo -c -o cmd-run-clisp.o cmd-run-clisp.c
(printf "#define ROS_REVISION \"" && ((which git>/dev/null&&[ -e ../.git ]&& \
	(git log -n 1 --oneline|cut -d' ' -f1| tr -d '\n'| tr -d '\r'))||printf "") && printf "\"\n") >> gend.h.tmp
(sh -c 'cd /usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell; pwd -W' 2>&1 >/dev/null && (printf "#define WIN_LISP_PATH \"" \
	echo `sh -c 'cd /usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell; pwd -W 2>/dev/null'`| tr -d '\n'| tr -d '\r' |\
	sed /\//\\/ \
	printf "\\\\\"\n")  >> gend.h.tmp) || printf ""
sh: line 0: cd: /usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell: No such file or directory
sh: line 0: pwd: -W: invalid option
pwd: usage: pwd [-LP]
cmp -s gend.h.tmp gend.h||cp gend.h.tmp gend.h
rm -f gend.h.tmp
cat gend.h
#define ROS_COMPILE_ENVIRONMENT "Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)"
#define ROS_REVISION ""
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-ecl.o -MD -MP -MF .deps/cmd-run-ecl.Tpo -c -o cmd-run-ecl.o cmd-run-ecl.c
mv -f .deps/util_system.Tpo .deps/util_system.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-abcl.o -MD -MP -MF .deps/cmd-run-abcl.Tpo -c -o cmd-run-abcl.o cmd-run-abcl.c
mv -f .deps/cmd-internal.Tpo .deps/cmd-internal.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-cmu.o -MD -MP -MF .deps/cmd-run-cmu.Tpo -c -o cmd-run-cmu.o cmd-run-cmu.c
mv -f .deps/util_dir.Tpo .deps/util_dir.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-run-acl.o -MD -MP -MF .deps/cmd-run-acl.Tpo -c -o cmd-run-acl.o cmd-run-acl.c
mv -f .deps/cmd-run-clisp.Tpo .deps/cmd-run-clisp.Po
mv -f .deps/cmd-run-ccl.Tpo .deps/cmd-run-ccl.Po
mv -f .deps/cmd-run-sbcl.Tpo .deps/cmd-run-sbcl.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-install.o -MD -MP -MF .deps/cmd-install.Tpo -c -o cmd-install.o cmd-install.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-install-sbcl-bin.o -MD -MP -MF .deps/cmd-install-sbcl-bin.Tpo -c -o cmd-install-sbcl-bin.o cmd-install-sbcl-bin.c
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-install-quicklisp.o -MD -MP -MF .deps/cmd-install-quicklisp.Tpo -c -o cmd-install-quicklisp.o cmd-install-quicklisp.c
mv -f .deps/cmd-run.Tpo .deps/cmd-run.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-help.o -MD -MP -MF .deps/cmd-help.Tpo -c -o cmd-help.o cmd-help.c
mv -f .deps/cmd-run-ecl.Tpo .deps/cmd-run-ecl.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-config.o -MD -MP -MF .deps/cmd-config.Tpo -c -o cmd-config.o cmd-config.c
mv -f .deps/cmd-run-abcl.Tpo .deps/cmd-run-abcl.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-setup.o -MD -MP -MF .deps/cmd-setup.Tpo -c -o cmd-setup.o cmd-setup.c
mv -f .deps/cmd-run-cmu.Tpo .deps/cmd-run-cmu.Po
clang -DHAVE_CONFIG_H -I. -I..  -DLISP_PATH=\"/usr/local/Cellar/roswell/0.0.3.46/share/common-lisp/source/roswell\"   -g -O2 -MT cmd-version.o -MD -MP -MF .deps/cmd-version.Tpo -c -o cmd-version.o cmd-version.c
mv -f .deps/cmd-run-acl.Tpo .deps/cmd-run-acl.Po
mv -f .deps/cmd-install-quicklisp.Tpo .deps/cmd-install-quicklisp.Po
mv -f .deps/cmd-install-sbcl-bin.Tpo .deps/cmd-install-sbcl-bin.Po
mv -f .deps/cmd-install.Tpo .deps/cmd-install.Po
mv -f .deps/cmd-help.Tpo .deps/cmd-help.Po
mv -f .deps/cmd-config.Tpo .deps/cmd-config.Po
mv -f .deps/cmd-setup.Tpo .deps/cmd-setup.Po
mv -f .deps/cmd-version.Tpo .deps/cmd-version.Po
clang  -g -O2   -o ros lsp.o opt.o download.o archive.o html.o util_list.o util.o util_string.o util_dir.o util_system.o cmd-internal.o cmd-version.o cmd-run.o cmd-run-sbcl.o cmd-run-ccl.o cmd-run-clisp.o cmd-run-ecl.o cmd-run-abcl.o cmd-run-cmu.o cmd-run-acl.o cmd-install.o cmd-install-sbcl-bin.o cmd-install-quicklisp.o cmd-help.o cmd-config.o cmd-setup.o  -lcurl
./ros setup --no-core;./ros ../scripts/man.ros ../documents/ros.html ../documents/ros.1
Installing sbcl-bin...
########################################################################## 100%
SBCL version is not specified. Downloading platform-table.html to see which version to install...
Installing sbcl-bin/1.2.11...
Downloading http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.11-x86-64-darwin-binary.tar.bz2
Failed to Download.
Downloading http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.10-x86-64-darwin-binary.tar.bz2
Failed to Download.
Installing sbcl-bin...
########################################################################## 100%
/bin/sh: line 1: 97978 Segmentation fault: 11  ./ros ../scripts/man.ros ../documents/ros.html ../documents/ros.1
make[1]: *** [../documents/ros.1] Error 139
make: *** [install-recursive] Error 1
==> Formula
Tap: snmsts/homebrew-roswell
Path: /usr/local/Library/Taps/snmsts/homebrew-roswell/roswell.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: ae8827439e7664d4cad7d66e5c78ea86da21b777
Last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: N/A
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: roswell 0.0.3.46 did not build
Logs:
     /var/root/Library/Logs/Homebrew/roswell/01.sh
     /var/root/Library/Logs/Homebrew/roswell/02.configure
     /var/root/Library/Logs/Homebrew/roswell/02.configure.cc
     /var/root/Library/Logs/Homebrew/roswell/03.make
     /var/root/Library/Logs/Homebrew/roswell/03.make.cc
     /var/root/Library/Logs/Homebrew/roswell/config.log

**Comment by snmsts** [comment]
I'm sorry late response.I didn't notice your reply...
It is quite difficult to understand the failure that http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.11-x86-64-darwin-binary.tar.bz2 but that should be the important part for building roswell.
I think it could be connection problem to sourceforge.net  from your place... and It is very difficult to reproduce from my place.

Could you download http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.11-x86-64-darwin-binary.tar.bz2 via browser or curl?

**Comment by snmsts** [comment]
next release's document are build different. close.
